# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков     OK!!!
GET {{baseUrl}}/
Content-Type: application/json

###

# создание датчика                          OK!!
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика                                 OK!!
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

#  добавление измерения                             OK!!
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику                   OK!!!
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
